# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18'
  displayName: 'Install Node.js'
- script: npm ci
  displayName: 'npm ci'
- script: npx playwright install
  displayName: 'Install Playwright browsers'
- script: npm run testapi
  displayName: 'Run Playwright tests'
  env:
    CI: 'true'
- script: |
    npx allure generate allure-results --clean -o allure-report
  displayName: 'Generate Allure report'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: 'allure-report'
    artifact: 'AllureReport'
  displayName: 'Publish Allure report'
- task: PublishAllureReport@1
  inputs:
    allureVersion: '3.0.0-beta.1'
    testResultsDir: 'allure-results'
    reportName: 'allure-report'
