# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18'
  displayName: 'Install Node.js'
- script: npm ci
  displayName: 'npm ci'
- script: npx playwright install
  displayName: 'Install Playwright browsers'
- script: npm run testapi
  displayName: 'Run Playwright tests'
  env:
    CI: 'true'
- task: PublishAllureReport@1
  inputs:
    reportDir: 'allure-results' 
